% Auto-generated by src/triple/generate_dynamics.py.
function out = bias_forces(q, dq, p)
%#codegen
  x = q(1); phi1 = q(2); phi2 = q(3); phi3 = q(4);
  dx = dq(1); dphi1 = dq(2); dphi2 = dq(3); dphi3 = dq(4);
  mc = p.mc; dc = p.dc; g = p.g;
  m1 = p.m(1); m2 = p.m(2); m3 = p.m(3);
  l1 = p.l(1); l2 = p.l(2); l3 = p.l(3);
  c1 = p.com(1); c2 = p.com(2); c3 = p.com(3);
  I1 = p.Iyy(1); I2 = p.Iyy(2); I3 = p.Iyy(3);
  d1c = p.dq(1); d2c = p.dq(2); d3c = p.dq(3);
  v1 = c1.*dphi1.^2.*m1.*sin(phi1) + c2.*dphi2.^2.*m2.*sin(phi2) + c3.*dphi3.^2.*m3.*sin(phi3) + dc.*dx + dphi1.^2.*l1.*m2.*sin(phi1) + dphi1.^2.*l1.*m3.*sin(phi1) + dphi2.^2.*l2.*m3.*sin(phi2);
  v2 = -c1.*g.*m1.*sin(phi1) + c2.*dphi2.^2.*l1.*m2.*sin(phi1 - phi2) + c3.*dphi3.^2.*l1.*m3.*sin(phi1 - phi3) + d1c.*dphi1 + d2c.*dphi1 - d2c.*dphi2 + dphi2.^2.*l1.*l2.*m3.*sin(phi1 - phi2) - g.*l1.*m2.*sin(phi1) - g.*l1.*m3.*sin(phi1);
  v3 = -c2.*dphi1.^2.*l1.*m2.*sin(phi1 - phi2) - c2.*g.*m2.*sin(phi2) + c3.*dphi3.^2.*l2.*m3.*sin(phi2 - phi3) - d2c.*dphi1 + d2c.*dphi2 + d3c.*dphi2 - d3c.*dphi3 - dphi1.^2.*l1.*l2.*m3.*sin(phi1 - phi2) - g.*l2.*m3.*sin(phi2);
  v4 = -c3.*dphi1.^2.*l1.*m3.*sin(phi1 - phi3) - c3.*dphi2.^2.*l2.*m3.*sin(phi2 - phi3) - c3.*g.*m3.*sin(phi3) - d3c.*dphi2 + d3c.*dphi3;
  out = [v1; v2; v3; v4];
end
