"""Generate mass_matrix.m and bias_forces.m in phi-from-upright coordinates.

These MATLAB-callable functions are auto-generated by computing the symbolic
expressions in sympy and writing the result as a single static MATLAB file
that takes (q, dq, p) and returns the requested quantity.  No algebraic
simplification or expand() is performed (those were timing out); the
expressions are copied verbatim.
"""
import sympy as sp
from pathlib import Path

OUTPUT_DIR = Path(__file__).resolve().parent

x, dx = sp.symbols('x dx', real=True)
phi1, dphi1, phi2, dphi2, phi3, dphi3 = sp.symbols('phi1 dphi1 phi2 dphi2 phi3 dphi3', real=True)
mc, dc, g = sp.symbols('mc dc g', positive=True, real=True)
m1, m2, m3 = sp.symbols('m1 m2 m3', positive=True, real=True)
l1, l2, l3 = sp.symbols('l1 l2 l3', positive=True, real=True)
c1, c2, c3 = sp.symbols('c1 c2 c3', positive=True, real=True)
I1, I2, I3 = sp.symbols('I1 I2 I3', positive=True, real=True)
d1c, d2c, d3c = sp.symbols('d1c d2c d3c', positive=True, real=True)
u = sp.symbols('u', real=True)

q = sp.Matrix([x, phi1, phi2, phi3])
dq = sp.Matrix([dx, dphi1, dphi2, dphi3])
p1 = sp.Matrix([x - c1*sp.sin(phi1), +c1*sp.cos(phi1)])
p2 = sp.Matrix([x - l1*sp.sin(phi1) - c2*sp.sin(phi2), +l1*sp.cos(phi1) + c2*sp.cos(phi2)])
p3 = sp.Matrix([x - l1*sp.sin(phi1) - l2*sp.sin(phi2) - c3*sp.sin(phi3),
                +l1*sp.cos(phi1) + l2*sp.cos(phi2) + c3*sp.cos(phi3)])
v1 = p1.jacobian(q)*dq
v2 = p2.jacobian(q)*dq
v3 = p3.jacobian(q)*dq
T = sp.Rational(1, 2)*mc*dx**2 + sp.Rational(1, 2)*m1*(v1.dot(v1)) + sp.Rational(1, 2)*I1*dphi1**2 \
    + sp.Rational(1, 2)*m2*(v2.dot(v2)) + sp.Rational(1, 2)*I2*dphi2**2 \
    + sp.Rational(1, 2)*m3*(v3.dot(v3)) + sp.Rational(1, 2)*I3*dphi3**2
V = m1*g*p1[1] + m2*g*p2[1] + m3*g*p3[1]
M = sp.hessian(T, dq)
Cmat = sp.zeros(4, 4)
for i in range(4):
    for j in range(4):
        s = 0
        for k in range(4):
            s += sp.Rational(1, 2)*(sp.diff(M[i, j], q[k]) + sp.diff(M[i, k], q[j]) - sp.diff(M[j, k], q[i])) * dq[k]
        Cmat[i, j] = s
D = sp.Matrix([[dc, 0, 0, 0],
               [0, d1c + d2c, -d2c, 0],
               [0, -d2c, d2c + d3c, -d3c],
               [0, 0, -d3c, d3c]])
Gvec = sp.Matrix([sp.diff(V, qi) for qi in q])
h = Cmat*dq + D*dq + Gvec

# Write mass_matrix.m
def matstr(e):
    return sp.octave_code(sp.simplify(sp.expand(e)))

def save(name, exprs, mode='matrix'):
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_DIR / (name + '.m'), 'w') as f:
        f.write('% Auto-generated by src/triple/generate_dynamics.py.\n')
        f.write(f'function out = {name}(q, dq, p)\n')
        f.write('%#codegen\n')
        f.write('  x = q(1); phi1 = q(2); phi2 = q(3); phi3 = q(4);\n')
        f.write('  dx = dq(1); dphi1 = dq(2); dphi2 = dq(3); dphi3 = dq(4);\n')
        f.write('  mc = p.mc; dc = p.dc; g = p.g;\n')
        f.write('  m1 = p.m(1); m2 = p.m(2); m3 = p.m(3);\n')
        f.write('  l1 = p.l(1); l2 = p.l(2); l3 = p.l(3);\n')
        f.write('  c1 = p.com(1); c2 = p.com(2); c3 = p.com(3);\n')
        f.write('  I1 = p.Iyy(1); I2 = p.Iyy(2); I3 = p.Iyy(3);\n')
        f.write('  d1c = p.dq(1); d2c = p.dq(2); d3c = p.dq(3);\n')
        flat = []
        for e in exprs:
            flat.append(matstr(e))
        for k, expr in enumerate(flat, start=1):
            f.write(f'  v{k} = {expr};\n')
        if mode == 'matrix':
            rows = []
            for i in range(4):
                cols = ['v' + str(i*4 + j + 1) for j in range(4)]
                rows.append('[' + ', '.join(cols) + ']')
            f.write('  out = [' + '; '.join(rows) + '];\n')
        else:
            f.write('  out = [v1; v2; v3; v4];\n')
        f.write('end\n')

save('mass_matrix', [M[i, j] for i in range(4) for j in range(4)], mode='matrix')
save('bias_forces', [h[i] for i in range(4)], mode='vector')

# Verify at upright using the lambdify path: check that h = 0 and acc = 0 when
# phi = 0 and dphi = 0, dx = 0, u = 0.
M_e = M.subs({x: 0, phi1: 0, phi2: 0, phi3: 0})
h_e = h.subs({x: 0, phi1: 0, phi2: 0, phi3: 0, dx: 0, dphi1: 0, dphi2: 0, dphi3: 0})
print('h_eq =', list(h_e))
print('G_eq =', list(Gvec.subs({x: 0, phi1: 0, phi2: 0, phi3: 0})))
print('M_eq =')
for row in M_e.tolist():
    print(' ', row)
