% Auto-generated by src/triple/generate_dynamics.py.
function out = mass_matrix(q, dq, p)
%#codegen
  x = q(1); phi1 = q(2); phi2 = q(3); phi3 = q(4);
  dx = dq(1); dphi1 = dq(2); dphi2 = dq(3); dphi3 = dq(4);
  mc = p.mc; dc = p.dc; g = p.g;
  m1 = p.m(1); m2 = p.m(2); m3 = p.m(3);
  l1 = p.l(1); l2 = p.l(2); l3 = p.l(3);
  c1 = p.com(1); c2 = p.com(2); c3 = p.com(3);
  I1 = p.Iyy(1); I2 = p.Iyy(2); I3 = p.Iyy(3);
  d1c = p.dq(1); d2c = p.dq(2); d3c = p.dq(3);
  v1 = m1 + m2 + m3 + mc;
  v2 = (-c1.*m1 - l1.*m2 - l1.*m3).*cos(phi1);
  v3 = (-c2.*m2 - l2.*m3).*cos(phi2);
  v4 = -c3.*m3.*cos(phi3);
  v5 = (-c1.*m1 - l1.*m2 - l1.*m3).*cos(phi1);
  v6 = I1 + c1.^2.*m1 + l1.^2.*m2 + l1.^2.*m3;
  v7 = l1.*(c2.*m2 + l2.*m3).*cos(phi1 - phi2);
  v8 = c3.*l1.*m3.*cos(phi1 - phi3);
  v9 = (-c2.*m2 - l2.*m3).*cos(phi2);
  v10 = l1.*(c2.*m2 + l2.*m3).*cos(phi1 - phi2);
  v11 = I2 + c2.^2.*m2 + l2.^2.*m3;
  v12 = c3.*l2.*m3.*cos(phi2 - phi3);
  v13 = -c3.*m3.*cos(phi3);
  v14 = c3.*l1.*m3.*cos(phi1 - phi3);
  v15 = c3.*l2.*m3.*cos(phi2 - phi3);
  v16 = I3 + c3.^2.*m3;
  out = [[v1, v2, v3, v4]; [v5, v6, v7, v8]; [v9, v10, v11, v12]; [v13, v14, v15, v16]];
end
