function regenerate_dynamics()
%DERIVE_MODEL  Run the host-side derivation of the TIPy dynamic model.
%
%   The MATLAB-callable functions mass_matrix.m and bias_forces.m are
%   generated by src/triple/generate_dynamics.py using symbolic
%   algebra in the phi (angle-from-upright) convention.  This entry point
%   simply documents the workflow and reminds the user how to regenerate.
%
%   Run on the host (not inside the container):
%     uv run --with sympy python src/triple/generate_dynamics.py
%
%   The output files are committed beside this function and loaded by
%   dynamics at simulation time.

    fprintf(['regenerate_dynamics.m does not perform symbolic algebra. Run\n', ...
             '   uv run --with sympy python src/triple/generate_dynamics.py\n', ...
             'on the host to regenerate mass_matrix.m and bias_forces.m.\n']);
end
